steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.cloudrun
      - --build-arg
      - BACKEND_URL=${_BACKEND_URL}
      - --build-arg
      - VITE_API_URL=
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/taskmanager/frontend:latest
      - .
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/taskmanager/frontend:latest
substitutions:
  _BACKEND_URL: http://localhost:8080
  _REGION: europe-west1
